services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: realestate_app
    volumes:
      - ${APP_PATH}:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - postgres
      - redis
      - mongodb
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MONGO_DB_HOST: ${MONGO_DB_HOST}
      MONGO_DB_PORT: ${MONGO_DB_PORT}
      MONGO_DB_DATABASE: ${MONGO_DB_DATABASE}
      MONGO_URI: ${MONGO_URI}
  postgres:
    image: postgres:15
    container_name: realestate_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
  redis:
    image: redis:alpine
    container_name: realestate_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - app-network
  mongodb:
    image: mongo:6
    container_name: realestate_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  pgdata:
  redisdata:
  mongodata:
